export { default as AwardsFrame } from './awards'
export { default as BiographyFrame } from './bio'
export { default as ContactFrame } from './contact'
export { default as CVFrame } from './cv'
export { default as ExperienceFrame } from './experience'
export { default as PublicationsFrame } from './publications'
